Benchmark Tests for FNO and DeepONets
SciML/NeuralOperators.jl pull request #17
Opened 2024-07-26 00:39 UTC by ayushinav

To fix #13 

* [x] comparison with neuraloperators
* [x] comparison with deepxde
* [] comparison with Flux variant
* [ ] GPU comparisons 

I had some issues with CUDA and all when installing torch CUDA toolkit.

2024-07-26 00:44 UTC, ayushinav commented
I guess a more appropriate place for this would be `SciMLBenchmarks`?

2024-07-26 00:46 UTC, avik-pal commented
Yes the CPU ones can go to SciMLBenchmarks. How are the julia native ones so slow? Did you run the profiler to see where the bottlenecks are?

2024-07-28 03:43 UTC, ayushinav commented
For DeepONet, most of the time goes to the layers, iiuc
![image](https://github.com/user-attachments/assets/e6e981f9-2493-4b35-8c6b-ccb65c65be26)


For FNOs, ig ffts are a bit expensive
![image](https://github.com/user-attachments/assets/1a750ee3-66c3-4fea-97e9-18fa40f6f4fb)

2024-07-28 05:37 UTC, avik-pal commented
Couple of things to check:

1. Load `MKL.jl` before calling the neural networks
2. Is the number of threads consistent between julia and python?

2024-07-28 05:39 UTC, avik-pal commented
Also that `compile` function might be compiling the torch model with dynamo. It is pretty much impossible to beat that with Lux running in eager mode. You could try and compile the DeepONet model with https://github.com/EnzymeAD/Reactant.jl/pull/55 and see the performance.

2024-07-30 00:54 UTC, avik-pal commented
Also looking at the plots you are on quite an old version of LuxLib, update it, and it should address some performance

2024-07-30 02:59 UTC, avik-pal commented
@ayushinav can you install https://github.com/LuxDL/LuxLib.jl/pull/111 and let me know how the performance is?

2024-08-03 16:05 UTC, avik-pal commented
I checked the recent lux releases. The current problems are

1. `__project` isn't fast enough. This needs to be rewritten to use LoopVectorization on CPU
2. `batched_mul` -- I am looking into this in LuxLib, this is quite easy to fix
3. allocations are expensive. Nothing much we can do there honestly.

2024-08-03 22:09 UTC, ChrisRackauckas commented
Can we make this into a SciMLBenchmarks script? That will be easier to maintain in the long run.

We can make that support GPU

2024-08-04 17:46 UTC, avik-pal commented
Also for python setup a `pyproject.toml` file so that setting up the benchmarks is easier

2024-08-04 20:48 UTC, avik-pal requested changes

2024-08-04 20:48 UTC, avik-pal commented on bench/pytorch.py
> +)
The dimensions are wrong here.

The julia version has sizes:

```julia
julia> size(u)
(32, 64)

julia> size(y)
(1, 128, 64)
```

while the pytorch versions have `(64, 32)` and `(64, 1)`

2024-08-04 20:58 UTC, avik-pal commented
Haven't looked into the FNO version much, but that will most likely need https://github.com/LuxDL/LuxLib.jl/issues/118 for performance. To summarize the issue there:

1. `gelu` and friends are surprisingly expensive operations, and fusing them into the `fused_dense` operations slows down the entire loop. But that is not true in general. For example, tanh/relu/abs, etc. can and should be fused into the main loop for performance. So we need to extend the current implementation with additional traits to see which activations can be fused for performance.
2. But the main perf gain will come from better gradient ops -- even for gelu. Currently, we fail to use LoopVectorization in that case but if we hardcode some of the common cases the performance will significantly improve.

2024-08-07 01:51 UTC, avik-pal commented
@ayushinav can we get this finished?

2024-08-08 22:46 UTC, avik-pal commented
@ayushinav bump

2024-08-08 22:50 UTC, ayushinav commented
@avik-pal 
Yes, I'm on this. I need to write the gradients for the new  `__project`s using LoopVectorization. The projection becomes faster then, but there isn't a significant speed up for the overall network.

2024-08-08 22:53 UTC, avik-pal commented
Do that in a separate PR, let's get the benchmarks aligned first. The pytorch ones use a different size it seems.

2024-08-09 03:03 UTC, ayushinav commented
The sizes are now aligned. The python variant of DeepONet only supports 1 eval point in a batch, and the Flux variant doesn't support batching. To have the same size for inputs, I made the batch size and the eval points same to compare with both the variants.

The Flux variant of FNO only supported a fixed length of kernels, which is fixed [here](650103186fa4e69fe7a652e2e201d8a4403761f7).

The difference in size now is because python uses `(batch_size, N)` whereas julia uses `(N, batch_size)`

2024-08-09 04:55 UTC, avik-pal commented
I am guessing the overhead in FNO is currently from fft?

2024-08-09 05:22 UTC, ayushinav commented
Fair share of fft and matmuladd, though the share of later has increased

![image](https://github.com/user-attachments/assets/091eeaf1-c29b-4983-b4d1-c2ab9e781e0c)

2024-08-09 07:18 UTC, avik-pal commented
Can you also profile the backward pass for the FNO? I am surprised it is that bad

2024-08-10 02:21 UTC, ayushinav commented
For mse loss, profiling the backward as `gradient(ps -> loss(first(model(x, ps, st)), y), ps)` 

![image](https://github.com/user-attachments/assets/cd5711ca-72fd-465d-9ddb-340fe62fdcc4)

2024-08-14 06:05 UTC, avik-pal commented
using the permuted formulation it is now all just fft time in forward and backward. It is quite surprising that our FFT is so much slower than pytorch.

@ayushinav might be worth giving https://github.com/Taaitaaiger/RustFFT.jl a shot and checking the  performance on CPUs

2026-01-23 19:16 UTC, closed without merging